import 'package:flutter/material.dart';

import '../models/app_module.dart';

class ModuleRegistry {
  static const List<AppModule> all = [
    AppModule(
      key: 'dashboard',
      title: 'Inicio',
      icon: Icons.space_dashboard_rounded,
      color: Color(0xFF5B7CFA),
      requiredPermission: 'dashboard.view',
      description: 'KPIs y actividad en tiempo real',
      implemented: true,
    ),
    AppModule(
      key: 'quality',
      title: 'Calidad',
      icon: Icons.verified_user_rounded,
      color: Color(0xFF6D5EF9),
      requiredPermission: 'quality.view',
      implemented: true,
    ),
    AppModule(
      key: 'incidents',
      title: 'Incidencias',
      icon: Icons.warning_amber_rounded,
      color: Color(0xFFFF6B57),
      requiredPermission: 'incidents.view',
      implemented: true,
    ),
    AppModule(
      key: 'training',
      title: 'Formación',
      icon: Icons.school_rounded,
      color: Color(0xFF22B07D),
      requiredPermission: 'training.view',
      description: 'Formación presencial y online',
      implemented: true,
    ),
    AppModule(
      key: 'documents',
      title: 'Documentos',
      icon: Icons.description_rounded,
      color: Color(0xFF4D84FF),
      requiredPermission: 'documents.view',
      implemented: true,
    ),
    AppModule(
      key: 'profile',
      title: 'Mi perfil',
      icon: Icons.account_circle_outlined,
      color: Color(0xFF2563EB),
      requiredPermission: null,
      implemented: true,
    ),
    AppModule(
      key: 'security',
      title: 'Seguridad',
      icon: Icons.shield_outlined,
      color: Color(0xFF0F766E),
      requiredPermission: null,
      implemented: true,
    ),
    AppModule(
      key: 'information',
      title: 'Información entregada',
      icon: Icons.inventory_2_outlined,
      color: Color(0xFF0891B2),
      requiredPermission: null,
      implemented: true,
    ),
    AppModule(
      key: 'payroll',
      title: 'Nóminas',
      icon: Icons.receipt_long_rounded,
      color: Color(0xFF64748B),
      requiredPermission: null,
      description: 'Documentos salariales del portal',
      implemented: true,
    ),
    AppModule(
      key: 'recruitment',
      title: 'Reclutamiento',
      icon: Icons.person_search_rounded,
      color: Color(0xFF8E66FF),
      requiredPermission: 'recruitment.view',
      implemented: true,
    ),
    AppModule(
      key: 'reservas',
      title: 'Reservas',
      icon: Icons.calendar_month_rounded,
      color: Color(0xFF4F46E5),
      requiredPermission: null,
      description: 'Reserva servicios y recursos',
      implemented: true,
    ),
    AppModule(
      key: 'planning',
      title: 'Planificación',
      icon: Icons.event_note_rounded,
      color: Color(0xFFFF8C42),
      requiredPermission: 'planning.view',
      description: 'Objetivos, planes de acción y químicos',
      implemented: true,
    ),
    AppModule(
      key: 'health',
      title: 'Vigilancia Salud',
      icon: Icons.monitor_heart_rounded,
      color: Color(0xFF7D5BFF),
      requiredPermission: 'health.view',
      implemented: true,
    ),
    AppModule(
      key: 'normative',
      title: 'Normativa',
      icon: Icons.gavel_rounded,
      color: Color(0xFF0EA5E9),
      requiredPermission: 'normative.view',
      implemented: true,
    ),
    AppModule(
      key: 'equipment',
      title: 'Equipos',
      icon: Icons.precision_manufacturing_rounded,
      color: Color(0xFFF59E0B),
      requiredPermission: 'equipment.view',
      implemented: true,
    ),
    AppModule(
      key: 'publications',
      title: 'Publicaciones',
      icon: Icons.article_outlined,
      color: Color(0xFF7C3AED),
      requiredPermission: null,
      implemented: true,
    ),
    AppModule(
      key: 'permissions',
      title: 'Permisos y roles',
      icon: Icons.fact_check_rounded,
      color: Color(0xFF38A169),
      requiredPermission: 'permissions.view',
      description: 'Roles y aprobaciones internas',
      implemented: true,
    ),
    AppModule(
      key: 'communications',
      title: 'Comunicaciones',
      icon: Icons.chat_bubble_outline_rounded,
      color: Color(0xFF3B82F6),
      requiredPermission: 'communications.view',
      description: 'Comunicaciones y sugerencias',
      implemented: true,
    ),
    AppModule(
      key: 'suppliers',
      title: 'Proveedores',
      icon: Icons.local_shipping_rounded,
      color: Color(0xFFB45309),
      requiredPermission: 'suppliers.view',
      implemented: true,
    ),
    AppModule(
      key: 'portal',
      title: 'Portal',
      icon: Icons.open_in_browser_rounded,
      color: Color(0xFFEC4899),
      requiredPermission: 'portal.view',
      description: 'Accesos portal, autoservicio y nóminas',
      implemented: true,
    ),
    AppModule(
      key: 'organization',
      title: 'Organización',
      icon: Icons.account_tree_rounded,
      color: Color(0xFF14B8A6),
      requiredPermission: 'organization.view',
      description: 'Pendiente de integrar con estructura organizativa',
      implemented: false,
    ),
    AppModule(
      key: 'purchases',
      title: 'Compras',
      icon: Icons.shopping_cart_checkout_rounded,
      color: Color(0xFF0EA5E9),
      requiredPermission: null,
      description: 'Productos, códigos y recepción',
      implemented: true,
    ),
    AppModule(
      key: 'maintenance',
      title: 'Mantenimiento',
      icon: Icons.build_circle_rounded,
      color: Color(0xFFF59E0B),
      requiredPermission: 'maintenance.view',
      description: 'Solicitudes y equipos enlazados con calidad',
      implemented: true,
    ),
  ];
}
