import 'package:flutter/material.dart';

import '../models/app_module.dart';

class ModuleRegistry {
  static const List<AppModule> all = [
    AppModule(
      key: 'incidents',
      title: 'Incidencias',
      icon: Icons.warning_amber_rounded,
      color: Color(0xFFFF6B57),
      requiredPermission: 'incidents.view',
      description: 'Registro, seguimiento y cierre de incidencias de tu unidad',
      implemented: true,
    ),
    AppModule(
      key: 'training',
      title: 'Formación',
      icon: Icons.school_rounded,
      color: Color(0xFF22B07D),
      requiredPermission: 'training.view',
      description: 'Formación presencial y online',
      implemented: true,
    ),
    AppModule(
      key: 'documents',
      title: 'Documentos',
      icon: Icons.description_rounded,
      color: Color(0xFF4D84FF),
      requiredPermission: 'documents.view',
      description: 'Consulta y descarga de documentos disponibles para ti',
      implemented: true,
    ),
    AppModule(
      key: 'security',
      title: 'Seguridad',
      icon: Icons.shield_outlined,
      color: Color(0xFF0F766E),
      requiredPermission: null,
      description: 'Procedimientos y documentación de seguridad',
      implemented: true,
    ),
    AppModule(
      key: 'information',
      title: 'Información entregada',
      icon: Icons.inventory_2_outlined,
      color: Color(0xFF0891B2),
      requiredPermission: null,
      description: 'Información y documentación entregada al usuario',
      implemented: true,
    ),
    AppModule(
      key: 'payroll',
      title: 'Nóminas',
      icon: Icons.receipt_long_rounded,
      color: Color(0xFF64748B),
      requiredPermission: null,
      description: 'Documentos salariales del portal',
      implemented: true,
    ),
    AppModule(
      key: 'recruitment',
      title: 'Reclutamiento',
      icon: Icons.person_search_rounded,
      color: Color(0xFF8E66FF),
      requiredPermission: 'recruitment.view',
      description: 'Procesos de selección y seguimiento de candidaturas',
      implemented: true,
    ),
    AppModule(
      key: 'reservas',
      title: 'Reservas',
      icon: Icons.calendar_month_rounded,
      color: Color(0xFF4F46E5),
      requiredPermission: null,
      description: 'Consulta disponibilidad y gestiona reservas de servicios y recursos',
      implemented: true,
    ),
    AppModule(
      key: 'planning',
      title: 'Planificación',
      icon: Icons.event_note_rounded,
      color: Color(0xFFFF8C42),
      requiredPermission: 'planning.view',
      description: 'Objetivos, planes de acción, químicos e informes',
      implemented: true,
    ),
    AppModule(
      key: 'health',
      title: 'Vigilancia Salud',
      icon: Icons.monitor_heart_rounded,
      color: Color(0xFF7D5BFF),
      requiredPermission: 'health.view',
      description: 'Seguimiento de vigilancia de la salud',
      implemented: true,
    ),
    AppModule(
      key: 'normative',
      title: 'Normativa',
      icon: Icons.gavel_rounded,
      color: Color(0xFF0EA5E9),
      requiredPermission: 'normative.view',
      description: 'Consulta de normativa y documentación aplicable',
      implemented: true,
    ),
    AppModule(
      key: 'equipment',
      title: 'Equipos',
      icon: Icons.precision_manufacturing_rounded,
      color: Color(0xFFF59E0B),
      requiredPermission: 'equipment.view',
      description: 'Inventario y seguimiento de equipos asociados a calidad',
      implemented: true,
    ),
    AppModule(
      key: 'publications',
      title: 'Publicaciones',
      icon: Icons.article_outlined,
      color: Color(0xFF7C3AED),
      requiredPermission: null,
      description: 'Consulta de publicaciones y contenidos informativos',
      implemented: true,
    ),
    AppModule(
      key: 'permissions',
      title: 'Permisos y roles',
      icon: Icons.fact_check_rounded,
      color: Color(0xFF38A169),
      requiredPermission: 'permissions.view',
      description: 'Roles y aprobaciones internas',
      implemented: true,
    ),
    AppModule(
      key: 'communications',
      title: 'Comunicaciones',
      icon: Icons.chat_bubble_outline_rounded,
      color: Color(0xFF3B82F6),
      requiredPermission: 'communications.view',
      description: 'Comunicaciones, avisos y sugerencias',
      implemented: true,
    ),
    AppModule(
      key: 'suppliers',
      title: 'Proveedores',
      icon: Icons.local_shipping_rounded,
      color: Color(0xFFB45309),
      requiredPermission: 'suppliers.view',
      description: 'Gestión y seguimiento de proveedores',
      implemented: true,
    ),
    AppModule(
      key: 'organization',
      title: 'Organización',
      icon: Icons.account_tree_rounded,
      color: Color(0xFF14B8A6),
      requiredPermission: 'organization.view',
      description: 'Pendiente de integrar con estructura organizativa',
      implemented: false,
    ),
    AppModule(
      key: 'purchases',
      title: 'Compras',
      icon: Icons.shopping_cart_checkout_rounded,
      color: Color(0xFF0EA5E9),
      requiredPermission: null,
      description: 'Consulta de productos, códigos y recepción de compras',
      implemented: true,
    ),
    AppModule(
      key: 'maintenance',
      title: 'Mantenimiento',
      icon: Icons.build_circle_rounded,
      color: Color(0xFFF59E0B),
      requiredPermission: 'maintenance.view',
      description: 'Solicitudes de mantenimiento y equipos enlazados con calidad',
      implemented: true,
    ),
  ];
}
